/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Swing;

import dmp.*;
import conexion.*;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class RegMed extends javax.swing.JFrame {

    UsuarioMedico um;
    ConexionSQL csql;
    IniSesion is;
    Registro regist;
    PreguntaClave pc;

    public RegMed() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_salir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtDni = new javax.swing.JTextField();
        txtFechaNacimiento = new javax.swing.JTextField();
        txtMatricula = new javax.swing.JTextField();
        txtEspecialidad = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        txtSexo = new javax.swing.JComboBox<>();
        btn_registrar = new javax.swing.JButton();
        btn_volver = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtLocalidad = new javax.swing.JTextField();
        jLabel1RegMed = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Cerrar2.png"))); // NOI18N
        btn_salir.setBorder(null);
        btn_salir.setBorderPainted(false);
        btn_salir.setContentAreaFilled(false);
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });
        getContentPane().add(btn_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Usuario");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Contraseña");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nombre");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Apellido");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Dni");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Fecha Nacimiento");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Matricula");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Especialidad");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Telefono");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Correo");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Sexo");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 560, -1, -1));

        txtUsuario.setBackground(new java.awt.Color(153, 255, 255));
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 170, 25));

        txtNombre.setBackground(new java.awt.Color(153, 255, 255));
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 170, 25));

        txtApellido.setBackground(new java.awt.Color(153, 255, 255));
        txtApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoActionPerformed(evt);
            }
        });
        getContentPane().add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 170, 25));

        txtDni.setBackground(new java.awt.Color(153, 255, 255));
        txtDni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDniActionPerformed(evt);
            }
        });
        getContentPane().add(txtDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 170, 25));

        txtFechaNacimiento.setBackground(new java.awt.Color(153, 255, 255));
        txtFechaNacimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaNacimientoActionPerformed(evt);
            }
        });
        getContentPane().add(txtFechaNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 170, 25));

        txtMatricula.setBackground(new java.awt.Color(153, 255, 255));
        txtMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMatriculaActionPerformed(evt);
            }
        });
        getContentPane().add(txtMatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, 170, 25));

        txtEspecialidad.setBackground(new java.awt.Color(153, 255, 255));
        txtEspecialidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEspecialidadActionPerformed(evt);
            }
        });
        getContentPane().add(txtEspecialidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, 170, 25));

        txtTelefono.setBackground(new java.awt.Color(153, 255, 255));
        txtTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoActionPerformed(evt);
            }
        });
        getContentPane().add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 390, 170, 25));

        txtCorreo.setBackground(new java.awt.Color(153, 255, 255));
        txtCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoActionPerformed(evt);
            }
        });
        getContentPane().add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 430, 170, 25));

        txtPassword.setBackground(new java.awt.Color(153, 255, 255));
        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 170, 25));

        txtSexo.setBackground(new java.awt.Color(153, 255, 255));
        txtSexo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione:", "Masculino", "Femenino" }));
        txtSexo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtSexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSexoActionPerformed(evt);
            }
        });
        getContentPane().add(txtSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 560, 100, -1));

        btn_registrar.setBackground(new java.awt.Color(51, 102, 255));
        btn_registrar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_registrar.setForeground(new java.awt.Color(255, 255, 255));
        btn_registrar.setText("Registrar");
        btn_registrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registrarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 620, 100, -1));

        btn_volver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/atras.png"))); // NOI18N
        btn_volver.setBorder(null);
        btn_volver.setBorderPainted(false);
        btn_volver.setContentAreaFilled(false);
        btn_volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_volverActionPerformed(evt);
            }
        });
        getContentPane().add(btn_volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Direccion");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, -1, -1));

        txtDireccion.setBackground(new java.awt.Color(153, 255, 255));
        txtDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDireccionActionPerformed(evt);
            }
        });
        getContentPane().add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 470, 170, 25));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Registro De Médico");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Localidad");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 510, -1, -1));

        txtLocalidad.setBackground(new java.awt.Color(153, 255, 255));
        txtLocalidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLocalidadActionPerformed(evt);
            }
        });
        getContentPane().add(txtLocalidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 510, 170, 25));

        jLabel1RegMed.setBackground(new java.awt.Color(153, 255, 255));
        jLabel1RegMed.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1RegMed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/FndRegMed.png"))); // NOI18N
        getContentPane().add(jLabel1RegMed, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registrarActionPerformed

        String usuario, contraseña, nombre, apellido, dni, fechaNacimiento, matricula, especialidad, telefono, correo, direccion, localidad, sexo;
        um = new UsuarioMedico();
        csql = new ConexionSQL();

        usuario = (txtUsuario.getText());
        if (usuario.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor rellene todos los campos", "\nAdvertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        contraseña = (txtPassword.getText());
        if (contraseña.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor rellene todos los campos", "\nAdvertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        nombre = (txtNombre.getText());
        if (nombre.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor rellene todos los campos", "\nAdvertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        apellido = (txtApellido.getText());
        if (apellido.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor rellene todos los campos", "\nAdvertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        dni = (txtDni.getText());

        if (dni.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor rellene todos los campos", "\nAdvertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        fechaNacimiento = (txtFechaNacimiento.getText());
        if (fechaNacimiento.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor rellene todos los campos", "\nAdvertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        matricula = (txtMatricula.getText());
        if (matricula.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor rellene todos los campos", "\nAdvertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        correo = (txtCorreo.getText());
        if (correo.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor rellene todos los campos", "\nAdvertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        direccion = (txtDireccion.getText());
        if (direccion.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor rellene todos los campos", "\nAdvertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        localidad = (txtLocalidad.getText());
        if (localidad.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor rellene todos los campos", "\nAdvertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        sexo = txtSexo.getSelectedItem().toString();

        if (csql.verificarUsuario(txtUsuario.getText()) == false) {
            txtUsuario.setText("");
            JOptionPane.showMessageDialog(this, "Nombre de Usuario ya Existente", "\nAdvertencia", JOptionPane.WARNING_MESSAGE);
            csql.verificarUsuario(txtUsuario.getText());

        } else if (csql.verificarMatricula(txtMatricula.getText()) == false) {
            txtMatricula.setText("");
            JOptionPane.showMessageDialog(this, "Matricula Inexistente", "\nAdvertencia", JOptionPane.WARNING_MESSAGE);
            csql.verificarMatricula(txtMatricula.getText());
        } else {

            um.setUsuario(txtUsuario.getText());
            um.setContraseña(txtPassword.getText());
            um.setNombre(txtNombre.getText());
            um.setApellido(txtApellido.getText());
            um.setDni(txtDni.getText());
            um.setFechaNacimiento(txtFechaNacimiento.getText());
            um.setMatricula(txtMatricula.getText());
            um.setEspecialidad(txtEspecialidad.getText());
            um.setTelefono(txtTelefono.getText());
            um.setMail(txtCorreo.getText());
            um.setDireccion(txtDireccion.getText());
            um.setLocalidad(txtLocalidad.getText());
            um.setSexo(sexo);

            csql.insertMedico(um);

            try {
                if (csql.verificarConexion()) {
                    JOptionPane.showMessageDialog(null, "Registro Exitoso");
                } else {
                    JOptionPane.showMessageDialog(null, "Error de registro");
                }
            } catch (SQLException ex) {

            }
            int i = JOptionPane.showConfirmDialog(null, "¿Desea Establecer La Pregunta De Seguridad En Caso De Olvidar Su Contraseña?", "Pregunta De Seguridad", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (i != 1) {
                pc.setVisible(true);
                pc.user = txtUsuario.getText();
                this.setVisible(false);
                limpiar();
            } else {
                is = new IniSesion();
                is.setVisible(true);
                this.setVisible(false);
            }
        }
    }//GEN-LAST:event_btn_registrarActionPerformed

    private void txtCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoActionPerformed
        txtCorreo.transferFocus();
    }//GEN-LAST:event_txtCorreoActionPerformed

    private void txtTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoActionPerformed
        txtTelefono.transferFocus();
    }//GEN-LAST:event_txtTelefonoActionPerformed

    private void txtEspecialidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEspecialidadActionPerformed
        txtEspecialidad.transferFocus();
    }//GEN-LAST:event_txtEspecialidadActionPerformed

    private void txtMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMatriculaActionPerformed
        txtMatricula.transferFocus();
    }//GEN-LAST:event_txtMatriculaActionPerformed

    private void txtFechaNacimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaNacimientoActionPerformed
        txtFechaNacimiento.transferFocus();
    }//GEN-LAST:event_txtFechaNacimientoActionPerformed

    private void txtDniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDniActionPerformed
        txtDni.transferFocus();
    }//GEN-LAST:event_txtDniActionPerformed

    private void txtApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoActionPerformed
        txtApellido.transferFocus();
    }//GEN-LAST:event_txtApellidoActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        txtNombre.transferFocus();
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        txtPassword.transferFocus();
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        txtUsuario.transferFocus();
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
        System.exit(1);
    }//GEN-LAST:event_btn_salirActionPerformed

    private void txtSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSexoActionPerformed
        txtSexo.transferFocus();
    }//GEN-LAST:event_txtSexoActionPerformed

    private void btn_volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_volverActionPerformed
        regist = new Registro();
        regist.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_volverActionPerformed

    private void txtLocalidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLocalidadActionPerformed
        txtLocalidad.transferFocus();
    }//GEN-LAST:event_txtLocalidadActionPerformed

    private void txtDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDireccionActionPerformed
        txtDireccion.transferFocus();
    }//GEN-LAST:event_txtDireccionActionPerformed

    void limpiar() {
        txtUsuario.setText("");
        txtPassword.setText("");
        txtNombre.setText("");
        txtApellido.setText("");
        txtDni.setText("");
        txtFechaNacimiento.setText("");
        txtMatricula.setText("");
        txtEspecialidad.setText("");
        txtTelefono.setText("");
        txtCorreo.setText("");
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_registrar;
    private javax.swing.JButton btn_salir;
    private javax.swing.JButton btn_volver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel1RegMed;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtDni;
    private javax.swing.JTextField txtEspecialidad;
    private javax.swing.JTextField txtFechaNacimiento;
    private javax.swing.JTextField txtLocalidad;
    private javax.swing.JTextField txtMatricula;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JComboBox<String> txtSexo;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
